### ISSUE TITLE
wandb/local fails with docker-compose.yml

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/local#10]
The following command works fine for me:
```
❯ docker run --rm -it -p 8080:8080 --name wandb-local wandb/local

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
*** Loading settings...
2021/03/15 18:04:27 Created default user
2021/03/15 18:04:27 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 58
*** Setting up mysql database...
*** Configuring minio...
*** Starting wandb servers...
Bucket created successfully `local/local-files`.
*** Migrating database...
Successfully added arn:minio:sqs:wandb-local:_:redis
Loading custom chart definitions...
*** All services started
*** Access W&B at http://localhost:8080
```
However the following `docker-compose.yml` fails:
```yml
version: "3.9"
services:
  wandb:
    image: "wandb/local"
    ports:
      - 8080:8080
```
```
❯ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Starting jax-agents_wandb_1 ... done
Attaching to jax-agents_wandb_1
wandb_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
wandb_1  | *** Running /etc/my_init.d/01_enable-services.sh...
wandb_1  | *** Copying services to runit
wandb_1  | mv: cannot stat '/home/wandb/service/*': No such file or directory
wandb_1  | mv: cannot stat '/home/wandb/wandb-logrotate': No such file or directory
wandb_1  | *** Copying jobber template
wandb_1  | *** Enabling production mode
wandb_1  | ln: failed to create symbolic link '/etc/nginx/sites-enabled/wandb.conf': File exists
wandb_1  | *** /etc/my_init.d/01_enable-services.sh failed with status 1
wandb_1  |
wandb_1  | *** Killing all processes...
jax-agents_wandb_1 exited with code 1
```
I am a little new to docker-compose, but I thought that the two commands were effectively the same.

**Comment by ethanabrooks** [comment]
I'll add one very strange thing that I am observing. If I add a `command` field to the wandb service:
```yaml
version: "3.9"
services:
  wandb:
    image: "wandb/local"
    ports:
      - 8080:8080
    command: ["ls", "/home/wandb/"]
 ```
we see that the supposedly missing files and directories are present:

**Comment by vanpelt** [comment]
It seems like docker compose is mounting something into the container that's blowing away the local file system.  Can you run `docker inspect jax-agents_wandb_1` and see what "Mounts" are present?

**Comment by ethanabrooks** [comment]
```
        "Mounts": [
            {
                "Type": "volume",
                "Name": "jax-agents_wandb",
                "Source": "/var/lib/docker/volumes/jax-agents_wandb/_data",
                "Destination": "/vol",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
    ```

**Comment by vanpelt** [comment]
Hmm, when I ran `docker compose` locally it didn't give the volume a nice name, also since we're not mounting in `/home/wandb` that seems unlikely the cause.  I would try two things.

1. Run `docker pull wandb/local:0.9.38` and update your compose to use that explicit version.  It seems like you may have a corrupt version of the image locally somehow.
2. If that doesn't work, try `docker volume rm jax-agents_wandb`

**Comment by ethanabrooks** [comment]
So after doing that, the first run succeeded and the second run failed (same error). This is what I found with docker inspect:

        "Mounts": [
            {
                "Type": "volume",
                "Name": "12c185b41f5a47f4a9d3a5f3508725aa55db6f50b7ec0c8693ab734df3cf2e15",
                "Source": "/var/lib/docker/volumes/12c185b41f5a47f4a9d3a5f3508725aa55db6f50b7ec0c8693ab734df3cf2e15/_data",
                "Destination": "/vol",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

**Comment by ethanabrooks** [comment]
Ok I think this might have just been a function of my ignorance about docker-compose...
It looks like if I invoke `docker-compose down` between runs, things work fine.

**Comment by vanpelt** [comment]
Ahh, yeah that makes sense.  The state of the filesystem will be screwy without the `down` command.
