### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by lacek** [wandb/local#13]
Local server cannot be launch, neither with python command nor Docker.

With wandb python command:

```
$ wandb local -p 18080
wandb: W&B local started at http://localhost:18080 🚀
wandb: You can stop the server by running `docker stop wandb-local`
wandb: You can find your API key in your browser here: http://localhost:18080/authorize
wandb: Paste an API key from your profile and hit enter:
```

Browsing http://localhost:18080/authorize shows connection refused.
Executing `docker ps` show no container named `wandb-local`.

With Docker, container exit immediately with exit status 1:

```
$ docker run -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local:0.9.38
5d507573ca334b6970336158a84a8816644122af290a8d6f06eae7625b6b72cc
$ docker logs wandb-local
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 430, in <module>
    main(args)
  File "/sbin/my_init", line 341, in main
    export_envvars()
  File "/sbin/my_init", line 116, in export_envvars
    with open("/etc/container_environment/" + name, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/container_environment/PATH'
```

**Comment by vanpelt** [comment]
This is because the file system inside of your docker container is read only.  You either need to run the container as root, or configure your docker daemon to mount read / write filesystems.  How did you install Docker?

**Comment by lacek** [comment]
I tried on several Linux servers  and the same error was reproduced:

- Docker 18.06.1 on Ubuntu 14.04
- Docker 18.09.7 on Ubuntu 16.04
- Docker 19.03.8 on Ubuntu 16.04

The Docker were install by someone else. Based on the apt configuration, I guess they were installed using instructions provided on the Docker web site.

On the other hand, there isn't such error when the same command is run on Docker Desktop for Mac.

Per your advice, the server is started normally on Linux when the container is launched as root with `docker run -u root ...`. Please close the issue if this is an expected usage.

**Comment by cmsax** [comment]
Please update the documentation...

**Comment by vanpelt** [comment]
@cmsax what command worked for you?  Did you run `sudo docker run` or `docker run -u root`?

**Comment by cmsax** [comment]
`wandb local` & `docker run` & `sudo docker run` neither, `docker run -u root` worked for me too.

**Comment by vanpelt** [comment]
For anyone else finding this, the appropriate way to start the container when the default user / file permissions aren't working is:

`docker run --user "100000:0" ...`

Running the container as root is generally a bad idea and anything on our file system that needs to be written to has a gid of 0.
