### ISSUE TITLE
Upload to local server error!

### ISSUE THREAD

**Issue by syw2014** [wandb/local#14]
After training , when upload file to local server:
wandb version: 0.10.23

------------------
Failed to upload file: /tmp/tmpjtpi0i31wandb/ne7jqwp7-train/events.out.tfevents.1616653556.algo
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/old/retry.py", line 132, in wrapped_fn
    return retrier(*args, **kargs)
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 1125, in upload_file
    util.sentry_reraise(e)
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/util.py", line 120, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/root/anaconda3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 1113, in upload_file
    response.raise_for_status()
  File "/root/anaconda3/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 507 Server Error: Insufficient Storage for url: http://localhost:8080/local-files/jerryshi/keyword-spotting/1c8tsvqu/train/events.out.tfevents.1616653556.algo?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=01XAz2YEMdRALQUsVeH9tQ%3D%3D%2F20210325%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20210325T070627Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=27f061a308f957a4d6555a9ac613c85c70acc8455f86317fbdf86b615cf87b6a

**Comment by vanpelt** [comment]
This means you're disk has run out of space.  The trial version of wandb is just meant for testing purposes.  In production you'll want to license the instance and connect it to a cloud storage bucket so that you'll never run out of space.

**Comment by syw2014** [comment]
> This means you're disk has run out of space. The trial version of wandb is just meant for testing purposes. In production you'll want to license the instance and connect it to a cloud storage bucket so that you'll never run out of space.

Yes I know, But I confused there are still 500G left in my disk, and I found the event files(events.out.tfevents.1616653514.algo) created by tensorflow only 2.4G, why it report this error?

**Comment by vanpelt** [comment]
It's the docker volume that's full, not your local disk.  We mount a volume into the docker container named wandb.  If you run `docker volume inspect wandb` you'll see where the volume is physically located.  Depending on your operating system this may be within a VM that has disk space limitations.

**Comment by syw2014** [comment]
> It's the docker volume that's full, not your local disk. We mount a volume into the docker container named wandb. If you run `docker volume inspect wandb` you'll see where the volume is physically located. Depending on your operating system this may be within a VM that has disk space limitations.

OK， thank you for your reply！
