### ISSUE TITLE
Disabled users disappearing

### ISSUE THREAD

**Issue by carloalbertobarbano** [wandb/local#15]
Using the wandb/local version 0.9.38. 

As per title, once a user is disabled I cannot find any trace of it even if the "show disabled users" box is ticked in the /admin/users dashboard.

How can I re-enable them, or at least delete them so I can recreate new users with the same email address?

**Comment by davidwallacejackson** [comment]
@carloalbertobarbano  This is a known regression in 0.9.38. We just released 0.9.39 on Friday, which should fix it -- if it doesn't, please let us know and we'll reopen this.

**Comment by carloalbertobarbano** [comment]
Thanks, I do see them. However all the options are grayed out and I can't re-enable or delete them

![image](https://user-images.githubusercontent.com/13789437/112871580-ac5f1d80-90bf-11eb-9d17-79bcd7582219.png)

**Comment by vanpelt** [comment]
Hey @carloalbertobarbano the most recent release of wandb/local only allows one enabled user for an unlicensed copy of the software.  If you email me at `vanpelt@wandb.com` I can get you trial license or discuss a commercial license.

**Comment by carloalbertobarbano** [comment]
Got it. I applied for a free 3-user license as suggested in the users dashboard, thanks
