### ISSUE TITLE
Use WandB local without Docker Requirement?

### ISSUE THREAD

**Issue by LarsHill** [wandb/local#24]
Hi,

Looking eagerly for an alternative to TensorBoard, I discovered WandB to track and visualize training run hyperparameters and metrics. 
Since our client data cannot leave our servers, only the local version of WandB is an option.

Unfortunately I am not able to try it out due to the docker requirement for fireing up the UI. At my work place each developer works from within his own docker container on a computational cluster with access to several GPUs. Due to access right management only the admin has root rights to use the main docker deamon. From within a container this deamon is not reachable. Also installing Docker within this container (Docker in Docker) is not feasable.

Is it really necessary to fire up the UI via Docker? Maybe one could think of an alternative since I think especially for professional setups like ours (where Docker is used to manage access rigths for every developer) this is a hurdle.

Thanks in advance and best regards
Lars

Ps 1: @vanpelt I saw your nice demo of WandB local on youtube, so maybe you you have some input for me on this matter?
Ps 2: I know that [Aim](https://github.com/aimhubio/aim) recently added a dockerless option to use their tracking tool. Maybe something like that is also feasable for WandB local?

**Comment by vanpelt** [comment]
Hey Lars, our service depends on cloud storage and MySQL to function so running it outside of docker is not practical.  The best solution for you would be to run a single wandb server within your network that all docker containers can talk to over the network.  Send an email to contact@wandb.com to discuss the installation process and see if it would be a fit for your team.
