### ISSUE TITLE
Singularity support

### ISSUE THREAD

**Issue by StefanGStark** [wandb/local#28]
My compute environment supports singularity but not docker. Is there a way to run wandb after converting docker images to singularity?

**Comment by vanpelt** [comment]
Hey @StefanGStark if you want to run a local wandb server we strongly recommend you run this in kubernetes or a system designed for running web services.  This can be done seperate from the environment that runs compute and only requires a network connection to the web service.  That being said, we have had some customers convert our docker container and run in signularity but it's not officially supported or tested.

**Comment by augustoicaro** [comment]
For those needing a Singularity recipe, I made one based on the latest docker image:

```Dockerfile
BootStrap:docker
From:wandb/local

%environment

export WANDB_BASE_URL=http://$HOSTNAME:8080

%runscript

su wandb -c "my_init --no-kill-all-on-exit"
```

Be aware that if you don't use `--no-kill-all-on-exit`, it will kill all processes in your host. Also, you should run `killall nginx && killall runsv && killall mysqld` to be able to run the container again. You should use `wandb` user or you will have problems with MySQL.

My full run command is: `singularity run --writable-tmpfs -f --no-home -B wandb:/vol wandb-local.sif`
