### ISSUE TITLE
How can I migrate old data to a new computer?

### ISSUE THREAD

**Issue by myaisv** [wandb/local#29]
I copied the files from /var/lib/docker/volumes/wandb to the new server, but it doesn't work.
The wandb version is the same for both (wandb/local:0.9.41).

The first error that appears is:
`chmod: changing permissions of '/vol/env': Operation not permitted`
After changing the file owner of `/var/lib/docker/volumes/wandb/_data/env`,  this error has been solved. But  a new error appeared:
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
*** Loading settings...
*** Booting runit daemon...
*** Runit started as PID 59
*** Starting wandb servers...
./run: line 1: kill: (137) - No such process
./run: line 1: kill: (243) - No such process
./run: line 1: kill: (295) - No such process
./run: line 1: kill: (343) - No such process
./run: line 1: kill: (391) - No such process

```

Is there any solution for this?

**Comment by vanpelt** [comment]
Are you able to access the interface?  Something is failing to startup, it's likely permissions in `/var/lib/docker/volumes/wandb/_data/minio` and `/var/lib/docker/volumes/wandb/_data/mysql` that are incorrect.

**Comment by myaisv** [comment]
Thanks, I solved this problem by this command :)
`chmod 777 -R  /var/lib/docker/volumes/wandb/_data/`
