### ISSUE TITLE
fix_permissions bug on sshfs mounted volume

### ISSUE THREAD

**Issue by DavidPL1** [wandb/local#3]
First of all, I've been using the locally hosted wandb version for a few weeks now and I gotta say it's pretty awesome, good job!

I guess this is kind of a very special case, but I am using sshfs to mount a shared directory which is then used as docker volume.
I do not have root privileges on the network share, but with uid and gid mapping I can circumvent any permission problems. However, changing group ownership is not allowed for the host mounting the share, so the first exec command in the following find invocation (located in the fix_permissions script) exits with an error:
```
find "$d" \
    ! \( \
      -group 0 \
      -a -perm -g+rwX  \
    \) \
    -exec chgrp 0 {} \; \
    -exec chmod g+rwX {} \;
```
And I noticed that if an exec command returns an error, subsequent exec commands will not be executed, so the chmod command is never run in my case.

I'd suggest swapping the order of those two exec options, to ensure chmod is executed in any case.

**Comment by vanpelt** [comment]
Thanks @DavidPL1, that's some great sleuthing.  I'm worried that even if we do the chmod the instance won't function properly.  We start our container assuming we'll be assigned a random uid for the user but this user will be in the root group so as long as the root group has write access to the files we're good.  In your case if we can't control the group of the filesystem you'll likely need to run the container as root or as a user that has write permission to the filesystem thereby circumventing the need for us to alter the permissions.

**Comment by vanpelt** [comment]
I'll also note that for production use cases we eliminate the need for any persistent storage within the container.  We would connect an external MySQL server and S3 or equivalent object store for all persistence.

**Comment by DavidPL1** [comment]
Thanks for the swift answer @vanpelt.
Actually the container runs just fine when remapping both the uid and gid of the files inside the volume to 0 and ensuring the group permissions are set correctly (at least for now). The host of the share doesn't care if the container thinks it has root privileges.

Currently a production scale setup is somewhat too much overhead for my use case, as I am the only one using this wandb instance. I simply resorted to network storage, as I was running out of memory on my local machine.
I'm aware that this is a very unusual use case and this problem is easy to fix manually. I just wanted to bring it to your attention.

I was also wondering if it would somehow be possible to skip the permission check completely with some flag while starting the container, as the bigger the volume gets, the longer it takes to check permissions of each file. E.g. for my ~40 GB volume (shared over sshfs) it took about an hour.
As in my case I ensure that the permissions are correct beforehand, it would be nice saving some time with the possibility to skip this step. But I also get that introducing changes that only enhance the free plan experience might not be your priority :) 

PS: Just in case I happen to stumble on more (potential) problems like this one while fiddling around, is this the correct place to report such issues?

**Comment by vanpelt** [comment]
Good to hear @DavidPL1!  I just took a look at the code, when the container is started without specifying a uid we run fix_permissions.sh on everything that was mounted.  If you specify a uid >= 100000 we don't run fix_permissions.sh on the entire volume.  Can you try the following when starting the container (the key specifying a uid of 100000):

```
docker run --rm -d -v wandb:/vol -p 8080:8080 -u 100000 --name wandb-local wandb/local
```

Moving forward, this is the best place to raise any other issues you may hit.

**Comment by DavidPL1** [comment]
Thank you very much, using the `-u` option works for me.

Alright, if I encounter other problems, I'll open another issue here.
