### ISSUE TITLE
Local OIDC Connect

### ISSUE THREAD

**Issue by DanaHan** [wandb/local#31]
In 0.9.43 release:
“Made direct OIDC authentication possible in local servers” is proposed.

I have Dex OICD provider in my k8s.

Any guide to use it to grant in my intranet?

I have tried to set Auth0 domain to my dex server and callback URI to oidc/callback.

But Dex auth endpoint is /auth and wandb is /authorize. When I modify this path manually in broswer, I can finish login in dex page. But call back page is 405 error. 

Wandb/local is designed to use in intranet, so it is important to grant in local not through Auth0.
Any suggestions?

**Comment by vanpelt** [comment]
Hey @DanaHan we're working on improvements to this due out in the next release hopefully this week.  I'll add a link to documentation once that goes live.

**Comment by vanpelt** [comment]
@DanaHan here are beta instructions for configuring OIDC with version 0.9.45 of local:

Configuring a direct OIDC connection without Auth0 is currently in a beta status and subject to change.  You'll need to configure an OIDC application in your IDP that supports the implicit form_post token exchange to https://YOURINSTANCE/oidc/callback.  Then you can set the following environment variables to make our system connect to it.

```
AUTH0_CLIENT_ID=$CLIENT_ID_FROM_IDP
AUTH0_DOMAIN=$DOMAIN_WITHOUT_HTTPS_TO_IDP
GORILLA_OIDC_AUTHORIZE_PATH=$PATH_OF_THE_AUTHORIZE_ENDPOINT_ON_YOUR_IDP_DOMAIN
GORILLA_OIDC_JWK_URL=$FQDN_OF_THE_IDPS_JWK_URL
```

We're working on a better interface for configuring this that can use the OIDC discovery document.  You'll be ablke to find the authorize path and JWK url by looking at https://YOUR_IDP_DOMAIN/.well-known/openid-configuration

**Comment by DanaHan** [comment]
@vanpelt Thanks, I will try it.

**Comment by DanaHan** [comment]
I have tried this new version.
Now, I can enter auth page and get the auth result successd. But then I get a 405 error.
My openid-configuration is:
`{
  "issuer": "https://dex-wandb.svc:5556",
  "authorization_endpoint": "https://dex-wandb.svc:5556/auth",
  "token_endpoint": "https://dex-wandb.svc:5556/token",
  "jwks_uri": "https://dex-wandb.svc:5556/keys",
  "userinfo_endpoint": "https://dex-wandb.svc:5556/userinfo",
  "response_types_supported": [
    "code",
    "id_token",
    "token"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic"
  ],
  "claims_supported": [
    "aud",
    "email",
    "email_verified",
    "exp",
    "iat",
    "iss",
    "locale",
    "name",
    "sub"
  ]
}`

My Env setting in wandb is:
`- name: AUTH0_DOMAIN
              value: 'dex-wandb.svc:5556'
            - name: AUTH0_CLIENT_ID
              value: wandb-app
            - name: GORILLA_OIDC_AUTHORIZE_PATH
              value: auth
            - name: GORILLA_OIDC_JWK_URL
              value: 'dex-wandb.svc:5556/keys'
`

And in dex log output:
`time="2021-11-10T12:10:49Z" level=info msg="performing ldap search cn=Users,dc=local sub (&(objectClass=user)(sAMAccountName=dana))"

time="2021-11-10T12:10:49Z" level=info msg="username \"dana\" mapped to entry CN=dana@local,CN=Users,DC=local"

time="2021-11-10T12:10:49Z" level=info msg="login successful: connector \"AD\", username=\"dana\", preferred_username=\"\", email=\"dana@local\", groups=[]"

Sometimes, There is an output after the previous output:
`error msg="Failed to get auth request: not found"`

It seem that I have logged in successful in dex, but not return wandb in right way.

I debug in broswer:
`GET http://wandb.local/oidc/callback#access_token=XXXXXXXXX&expires_in=86399&id_token=XXXXXXXXX&state=A_GfRAcJ2HJtUmz0WGoy5w%3D%3D&token_type=bearer
[HTTP/1.1 405 Method Not Allowed 2ms]`

Any help?

**Comment by vanpelt** [comment]
Dex should be issuing a 302 redirect with a post body instead of GET request with the content in the query string...  Looking at your values, GORILLA_OIDC_JWK_URL should be set to http://dex-wandb.svc:5556/keys 

It might be that Dex or your version of dex doesn't support `response_mode=form_post`.  I found [this branch](https://github.com/ory/hydra/commit/7f9605ea2ed35fb266f10ad673ae6c77370ea19e) that added support, but I don't think it's in the mainline.

The next release of local will support the PKCE code exchange flow which Dex should definitely support.

**Comment by DanaHan** [comment]
@vanpelt Thanks for your great work. In 0.9.47,PKCE support has been added.
There are some changes in 0.9.47.
In 0.9.45:
name: GORILLA_OIDC_AUTHORIZE_PATH
value: auth
In 0.9.47:
name: GORILLA_OIDC_AUTHORIZE_PATH
value: /auth

And now, I get an error when I click login button:
We're sorry, but there was a problem authenticating your account: Invalid PKCE code exchange: Post "": unsupported protocol scheme ""

Any suggest to use PKCE?

**Comment by vanpelt** [comment]
Hey @DanaHan in 0.9.47 you shouldn't need the custom GORILLA_OIDC_AUTHORIZE_PATH in 0.9.47.  Instead you can configure the SSO provider directly in the ui at `/system-settings` or via environment variables:

```
OIDC_ISSUER=https://dex-wandb.svc:5556
OIDC_CLIENT_ID=XXXXXX
OIDC_AUTH_METHOD=pkce
```

The above environment variables should replace all of the previous variables you set, such as AUTH0_DOMAIN, AUTH0_CLIENT_ID, and GORILLA_OIDC_JWK_URL.

**Comment by DanaHan** [comment]
@vanpelt Thanks. I have successed to run wandb in my local server with DEX.
There are still 2 problems:
1. My dex uses a self-signed certificate. And it seems that wandb cannot start backend and show x509 certificate is authorized by an unknown authorized organization. I have to change DEX from https to http. Can you add a env parameter to ignore certificate check?
2. If I do not set HOST env parameter, when I click login button, It redirect uri to localhost:8080.
   But if I set HOST=192.168.1.X with my local ip, I can not access from internet by using frp.
   In 0.9.45, evenif I do not set HOST, login button will also redirect to the DEX correctly.

**Comment by vanpelt** [comment]
Hey @DanaHan,

1. I'm hesitant to implement ignoring the certificate.  A better option would be for you to add the self signed certificate to the trust chain.  Let me think about better ways to make this easy to setup.
2. Yep, this behavior changed in 0.9.47.  We'll sync internally about the best way to address this.  The next release isn't officially scheduled until early Feb, but we may be able to share a development release sooner.

**Comment by DanaHan** [comment]
@vanpelt I also need to report another bug.
When user login with SSO, I can input full name and username is UI at first time.
But in this situation, the email should be the same as username, and I can not change email in UI.
Next, if the user is invited to a team, an error is coming. The log shows that the email format is incorrect.
Now, I have to change email from mysql database directly, and all behaviors are correct.

**Comment by vanpelt** [comment]
Hey @DanaHan you need to configure your dex server to return the users email in the claims.  Our SSO keys off of the "email" attribute in the id token we receive from dex.  All users in wandb will have an email (which we get from dex) and a username which the user chooses the first time they access the instance.  Users can be invited by either email address or username.

**Comment by DanaHan** [comment]
@vanpelt 
Thanks. You are right.
I made a stupid error in my DEX config.
I set the mailattr to uid directly in the connector settings. So  the username and email are the same.
😅
