### ISSUE TITLE
Not possible to Login when starting container, without entering an email address

### ISSUE THREAD

**Issue by pbower** [wandb/local#32]
Under https://docs.wandb.ai/guides/self-hosted/local it states:

"**Authentication**
The base install of wandb/local starts with a default user local@wandb.com. The default password is perceptron. The frontend will attempt to login with this user automatically and prompt you to reset your password. Contact us at support@wandb.com to request a free upgrade to your license, from 1 user to 3 users."

However, upon going to the start screen with 0.9.42 it forces to the Signup page when choosing 'Login'. When one then tries to click 'Terms & Conditions', they are presented with another signup screen, and unable to login.

When entering 'local' as the user, it says 'username is already taken', instead of allowing the user to login as promised.

**Comment by vanpelt** [comment]
@pbower we force you to change the default user for security.  We'll fix the terms and conditions link issue, but you must signup with an email address and username that is not local to actually use a local instance.  We don't share this email address with any external services and it's only used to send notifications from the server itself.  

If you visit the service from an incognito window or clear your cookies it should take you through the signup flow.

**Comment by pbower** [comment]
Hi @vanpelt  , but when having already signed up, once cannot login? It just shows the signup window, and then says 'username already taken'.
So one needs to signup with a new account every time in order to login, rather than use the login?

This was not present in 0.9.41 but appears to have occurred since then.

**Comment by vanpelt** [comment]
@pbower I got a notification about a comment asking if you had to signup every time but it's not rendering on github for some reason...

You will only need to signup once and specifing your email, username and password.  Then as long as you've mounted a persistent volume into the container (which happens automatically when running `wandb local`) you can use that account to login.
