### ISSUE TITLE
RequestError (500): send request failed (original: Get "http://127.0.0.1:9000/local-files/yang***/*****/3k2xr8hc/wandb-metadata.json": dial tcp 127.0.0.1:9000: connect: connection refused)

### ISSUE THREAD

**Issue by JieGenius** [wandb/local#35]
When I update wandb-local from v0.9.39 to v0.9.43, I can't open website page. The error message is :
RequestError (500): send request failed (original: Get "http://127.0.0.1:9000/local-files/yang***/*****/3k2xr8hc/wandb-metadata.json": dial tcp 127.0.0.1:9000: connect: connection refused)

I don't know why to have a port 9000.
![image](https://user-images.githubusercontent.com/39705429/133925670-5f990069-aa40-403e-b16f-e2779a2f6545.png)

**Comment by vanpelt** [comment]
@JieGenius this indicates that the minio object store running inside of the container is not accepting connections.  I would try restarting the container.  If that doesn't work, you can exec into the container and see if there are any details in the following log file: /var/log/minio.log

**Comment by JieGenius** [comment]
@vanpelt Thank you! I have solved this problem by checking the log file. 
The message from the minio.log file:
`ERROR Invalid command line arguments: Cross-device mounts detected on path (/vol/minio) at following locations [/vol/minio/local-files/xxxxxx/warehouse]. Export path should not have any sub-mounts, refusing to start.
      > Please check the FS endpoint`
It works fine when I unmount another disc.
