### ISSUE TITLE
OIDC: /.well-known/jwks.json is hard-coded

### ISSUE THREAD

**Issue by elgalu** [wandb/local#50]
Hi, while trying to integrate OIDC we found that `/.well-known/jwks.json` url seems to be hard-coded.

Unfortunately our `jwks.json` file is located at a different url, namely `/.well-known/jwk_uris`

Would it be possible that the OIDC implementation of wandb/local changes so that it grabs the `"jwks_uri"` field from `/.well-known/openid-configuration` ? or to support a way to customize it, e.g. add `AUTH0_JWKS`

We're not using Google for this but as an example see https://accounts.google.com/.well-known/openid-configuration

**Comment by vanpelt** [comment]
Hey @elgalu the next release of wandb/local will allow you to connect custom OIDC providers more elgantly.  Until then, you can set the following environment variables to enable an external OIDC provider (this will only work in >=wandb/local:0.9.46)

```
GORILLA_OIDC_AUTHORIZE_PATH=/auth/realms/myteam/protocol/openid-connect/auth
GORILLA_AUTH_JWK_URL=https://sso.myidp.net/auth/realms/aiteam/protocol/openid-connect/certs
AUTH0_DOMAIN=sso.myidp.net
AUTH0_CLIENT_ID=XXXXXXXXXXXXXX
```

The identity provider currently must support the implicit form_post flow.  The next release of wandb/local will also support the PKCE code exchange flow.

**Comment by elgalu** [comment]
worked like a charm, thanks!
