### ISSUE TITLE
Tensorboard plugin not working

### ISSUE THREAD

**Issue by NDer100KG** [wandb/local#51]
Hi team WandB:

I am trying to use the function of syncing logs from tensorboard to wandb, and I also need the embedding projector function in tensorboard.

Although the charts have been synced to my wandb-local (assumed the codes are executing correctly? ), the tensorboard plugin seems not popped, as the following picture
![2](https://user-images.githubusercontent.com/37607859/148372767-1f3080dd-1142-4652-a410-ebbe3e5751be.png)

However, the same code running on `https://api.wandb.ai` justs works, as the following picture
![1](https://user-images.githubusercontent.com/37607859/148372319-38f5ec74-9b81-4898-a48a-4aaff3b146f5.png)

Should I manually add something in the container, or any other commands are suggested? 
Thanks

Here are the codes I am using:
```
import wandb
import numpy as np
import tensorflow as tf

wandb.init(project='test_tensorboard', sync_tensorboard=True)

log_writer = tf.summary.create_file_writer("logs")
with log_writer.as_default():
    for i in range(100):
        tf.summary.scalar("test", i, step = i)

```

**Comment by vanpelt** [comment]
@NDer100KG Automated tensorboard serving only works in our SaaS offering.  We're planning to implement support for our local installations in the future, but this would require a kubernetes cluster and additional infrastructure.
