### ISSUE TITLE
Installing wandb-local without docker support

### ISSUE THREAD

**Issue by WasifurRahman** [wandb/local#78]
Hi, I work in a system that does not have docker support. Is there any way I can still use wandb-local?

**Comment by ramit-wandb** [comment]
Hi @WasifurRahman,

While docker is not necessary, you will need some kind of containerization system that can run docker images, for e.g. Singularity could work here. That being said, we only officially support docker for Local, so there might be some unexpected bugs when running on Singularity.

**Comment by WasifurRahman** [comment]
Thanks a lot for the response. Just to add, I don't have internet or root access inside that system. However, I can download a docker tarball and import it inside that protected system. Is there any way to install and use docker -- to run wandb-local server -- without root access?

**Comment by ramit-wandb** [comment]
Hey @WasifurRahman,

Docker can not be installed without root access to your machine. Installing docker without root would be a major security concern.

**Comment by sheljoy** [comment]
wandb-local without docker is necessary for apple arm64.  wandb/local image from docker.io could not been pulled with docker on apple M2 silicon.
