### ISSUE TITLE
Can't restart a stopped contiainer

### ISSUE THREAD

**Issue by imyhxy** [wandb/local#8]
When restart a stopped `wandb/local` container, the container exited instantly.

**Comment by vanpelt** [comment]
Hey @imyhxy to restart the container you should run:

`docker stop wandb-local`, then run `wandb local` or manually start the container again with docker.

**Comment by imyhxy** [comment]
@vanpelt When restart the container with `docker start wandb-local`, the container existed instantly.

**Comment by vanpelt** [comment]
@imyhxy calling `docker start wandb-local` will not work if you don't have a container named wandb-local.  Calling `docker restart wandb-local` does not work either.  If you need to start a wandb local container, you should run `wandb local`.
